In [22]:
import numpy as np



def doublearray(x):
    M = np.ones((len(x),3),dtype = int)
    for i in range (0,len(x)):
        M[i,1] = x[i]
        M[i,2] = x[i]**2
    return M
def C(sigma):
    C = np.zeros((len(sigma),len(sigma)))
    for i in range (0, len(sigma)):
        C[i,i] = 1/(sigma[i]**2)
    return C

x = [58,210,202,198,158,165,201,157,131,166,160,186,125,218,146]

y = np.array([173,479,504,510,416,393,442,317,311,400,337,423,334,533,344])
M = doublearray(x)

M_T = M.transpose()

sigma = [15,27,14,30,16,14,25,52,16,34,31,42,26,16,22]
Cminos1 = C(sigma)

covTheta = np.linalg.inv(M_T.dot(Cminos1.dot(M)))
theta = covTheta.dot(M_T.dot(Cminos1.dot(y)))

print(covTheta)
print(theta)


[[ 1.51758042e+03 -2.15597260e+01  7.03886774e-02]
 [-2.15597260e+01  3.38574112e-01 -1.17158345e-03]
 [ 7.03886774e-02 -1.17158345e-03  4.20524669e-06]]
[7.25764961e+01 1.60453048e+00 2.25414508e-03]
